language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python setup.py pytest
deploy:
  provider: pypi
  user: jo-nas
  password:
    secure: asGByQr1Gmvb1xGo7tbCFEJUiFuN38Zf4c3D8F9ey8IRfIY3WXbduMkKWMWrK8YZsbydmo2aEw7vHpbLJGpOqdspLDLoXJlJr86O3/XMAXv5ny2qDgDi769Dluc255Mg5ltNZaXI4Irqx0/4k+MoVbQlgU5I/7f5QISwuQDSSfZZuOl9/ROEA8OKGRROwL8gHkpzhLvuzsNZm3TZRFRcVBUiqv88k8BOL4DN7dKL17fswiOsIlTZjdKypmYGDZySIZLG5GpOd0454BpeXeT5pzTKylX3L1D4k/4S4viT2I0rsmVEolmFWL2QdA55o6s4S5ty/3H+pWbvt90g/LUudCzEOuMxTZamgM1rzQntpYgG4SG+sB2j3ZE32KxGXYVHFJaDEcEGR+FXLvoTmxnQf2Vbjkyqo6qQ7duTzqpvOqt6CNbjE92jyTA/mc/bHNYs/DEBToh8OmEcWCFhccv79vXlbGWL+gCKsoFlpBMnw76ZGIiaYFsFiar1dJDVN+gk3uZ8ogRAb4kFIjBvbsHrr4Hi31cmcfGUH7j/T+IJj25vv1vCmUKH4lx86gvO+fx4j0c653SBPHfEYOxJwiMQzv8WHvtcnIKTPV6wvU2ZIGallI1VSx/rC1m/6a1LMlPr/Qc3st9zWGhL0MGfjnB5ezEl9qxykO+fH97Qx1DOpEw=
  on:
    tags: true
