language: python
python:
  - "3.6"

install:
  - python setup.py install

script:
  - python setup.py test

deploy:
  provider: pypi
  user: jo-nas
  password:
    secure: "HpFk7svW5FdchA7BgTmHmucHemltQiGMSo6wvBch1deIR66/ptDhc75dibr/AzOhijoCuh6ZdGBj9ka+6VrHmGLxehKRJdknBAeqL0GdiwGzhKOUWAQeegAoqEyITH66naa+vc3MPe781Ig5/cxud6bKlcWSM8SHh/5MWzNDffB5ta4SAUrxEd5Iz42DaIEEjtRDmy47SypakWH/OKOcNZw7Oii8LETnatmgAGOR5ejHlirqbvfwUzRnWPCiFAbShMNHDgMJmz6qJUFtagNmM21rYtrqn2dXjPaRGOYZTrcnvScOtJfJcacF4H9/Rt3XS0vgFNX/CkQnhoJWzzk7xytWe4cdvbmAyCW2dA90NTOTtzyTHN6LWJBwvYeaMy2z75M/2ww5rEnIxsswKQMN66BSBnM4UdKJrqXFASf2IuM34OH84sMKIw2++c3IFxqmPpQUjtLAtya+hMUmanBB5pvltoQyf4RfR13k8RgwHg+qPGBe8Rny51jJVTkcrWjB0jYEVnRQMfu3JeyAk2SrFqt1DUSexcYye5ySxdSOLD9/9wP0D56YixQ46BBNemahXee5wObpsNzpwWSftH+iB54y9jtBDcuaozndzvzmMqnl+tIlk4V3oCm2BqlKpdOciqGeovti6DmDOk9GBHITnwXwpStyyWQy+C6NInsyuec="
  on:
    tags: true